version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrms_app_container
    ports:
      - "8081:80"
    volumes:
      - ./HRMS:/var/www/html
    depends_on:
      - db
    networks:
      custom_network:
        aliases:
          - localhost
    environment:
      - MYSQL_HOST=localhost  # App container will refer to localhost

  db:
    image: mysql:8.0
    container_name: hrms_db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD=""  # Set to your desired password if needed
      MYSQL_DATABASE=hrms
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      custom_network:

networks:
  custom_network:
    driver: bridge
